//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitkund.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VitkundEntities : DbContext
    {
        public VitkundEntities()
            : base("name=VitkundEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBusinessidea> tblBusinessideas { get; set; }
        public virtual DbSet<tblChapter> tblChapters { get; set; }
        public virtual DbSet<tblTrendingBusiness> tblTrendingBusinesses { get; set; }
        public virtual DbSet<tblVideo> tblVideos { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
    }
}
