//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitkund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string State { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsRole { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string City { get; set; }
        public string PaymentId { get; set; }
        public string PlanAmount { get; set; }
    }
}
