//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitkund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Firm { get; set; }
        public Nullable<int> Education { get; set; }
        public Nullable<int> Profit { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> Premises { get; set; }
        public Nullable<int> Capital { get; set; }
        public Nullable<int> Raw { get; set; }
        public Nullable<int> Research { get; set; }
        public Nullable<int> Marketing { get; set; }
        public Nullable<int> Cibil { get; set; }
        public Nullable<int> BusinessExpertise { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> fk_admin { get; set; }
        public Nullable<int> Score { get; set; }
        public string Name { get; set; }
    }
}
