//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitkund.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVideo
    {
        public int Id { get; set; }
        public Nullable<int> fK_Chapter { get; set; }
        public string FileTitle { get; set; }
        public string VideoFile { get; set; }
        public string VideoImage { get; set; }
    }
}
